### ISSUE TITLE
Capability to print output in stdout

### ISSUE THREAD

**Issue by LeoBorai** [Michael-Liendo/url-status-checker#2]
Hi @Michael-Liendo!
Thanks for such a cool initiative, giving this a shot I thought it would be nice to have results
print to stdout and optionally write to a file.

One could also stream the output to a file if needed.

```bash
url-checker -t https://github.com > ./myfile.txt
```

**Comment by Michael-Liendo** [comment]
Hello @EstebanBorai 

Thanks for your suggestion. I agree that it would be useful to be able to print the program results directly to the console.
I am working on implementing this feature.

**Comment by Michael-Liendo** [comment]
Implemented in #3. thanks!
